server:
  port: 9090
  contextPath: /test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mba?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cacppacs
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl

logging:
  file: web-devil-test.log
